---
version: '3'

services:

  traefik:
    image: traefik:v1.7
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN}
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID
      - PUID
      - TZ
    command: --schedule "0 0 6 * * *" --label-enable --cleanup
    restart: unless-stopped

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    volumes:
      - ${CONFIG}/ddclient:/config
    environment:
      - PGID
      - PUID
      - TZ      
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DOWNLOAD}/watch:/watch
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:sabnzbd.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/tv:/tv
      - ${DATA}/anime:/anime
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8989"
      traefik.frontend.rule: "Host:sonarr.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/movies:/movies
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "7878"
      traefik.frontend.rule: "Host:radarr.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    ports:
      - "8686:8686"
    volumes:
      - ${CONFIG}/lidarr:/config
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/music:/music
    environment:
      - PGID
      - PUID
    labels:
      traefik.enable: "true"
      traefik.port: "8686"
      traefik.frontend.rule: "Host:lidarr.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    hostname: lazylibrarian
    ports:
      - "5299:5299"
    volumes:
      - ${CONFIG}/lazylibrarian:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/books:/books
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "5299"
      traefik.frontend.rule: "Host:lazylibrarian.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  mylar:
    image: linuxserver/mylar:latest
    container_name: mylar
    hostname: mylar
    ports:
      - "8090:8090"
    volumes:
      - ${CONFIG}/mylar:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/comics:/comics
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8090"
      traefik.frontend.rule: "Host:mylar.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra2:latest
    container_name: nzbhydra
    hostname: nzbhydra
    ports:
      - "5076:5076"
    volumes:
      - ${CONFIG}/nzbhydra2:/config
      - ${DOWNLOAD}/complete:/downloads
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "5076"
      traefik.frontend.rule: "Host:nzbhydra.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${DATA}/tv:/media/tv
      - ${DATA}/movies:/media/movies
      - ${DATA}/music:/media/music
      - ${DATA}/anime:/media/anime
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    labels:
      traefik.enable: "true"
      traefik.port: "32400"
      traefik.frontend.rule: "Host:plex.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  plexpy:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/plexpy:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8181"
      traefik.frontend.rule: "Host:tautulli.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    volumes:
      - ${CONFIG}/heimdall:/config
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    hostname: ombi
    ports:
      - "3579:3579"
    volumes:
      - ${CONFIG}/ombi:/config
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "3579"
      traefik.frontend.rule: "Host:ombi.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  flexget:
    image: cpoppema/docker-flexget
    container_name: flexget
    hostname: flexget
    ports:
      - "5050:5050"
    volumes:
      - ${CONFIG}/flexget:/config
      - ${DOWNLOAD}/watch:/watch
    environment:
      - PGID
      - PUID
      - WEB_PASSWD=pNTgQj4hfJPPiGVFt9re
    labels:
      traefik.enable: "true"
      traefik.port: "5050"
      traefik.frontend.rule: "Host:flexget.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
